kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  selector:
    app: httpd
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 80
  type: NodePort