apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: simple-web-server
spec:
  selector:
    app: httpd
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 80