# Edit php:7.4-apache-bullseye to add mysqlmod
# docker build __pathtodockerfile__ -t php:7.4-apache-bullseye-pdo_mysql

FROM php:7.4-apache-bullseye
RUN docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo pdo_mysql
