apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      # Le conteneur est toujour sur le master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - "true"
      # Définition du conteneur PHPMyAdmin 
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: PMA_HOST
            value: mysql-service
          - name: PMA_PORT
            value: "3306"
          - name: MYSQL_ROOT_PASSWORD
            value: root
---
# Service PHPMyAdmin
kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      protocol: TCP
      nodePort: 30081
      port: 80
      targetPort: 80
  type: NodePort