apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-iscsi-pv
spec:
  capacity:
    storage: 7.5Gi
  accessModes:
    - ReadWriteMany
  #volumeName: mysql-iscsi-pv
  storageClassName: mysql-iscsi-pv
  iscsi:
     targetPortal: 10.0.0.3
     iqn: iqn.2003-01.org.linux-iscsi.debian.x8664:sn.dd15bcd23550
     lun: 0
     fsType: 'ext4'
     readOnly: false