kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 750m
          requests:
            cpu: 700m
        volumeMounts: 
        - name: sql-db
          mountPath: /var/lib/mysql
          subPath: "mysql"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      volumes:
      - name: sql-db
        iscsi:
          targetPortal: 10.0.0.3
          iqn: iqn.2003-01.org.linux-iscsi.debian.x8664:sn.dd15bcd23550
          lun: 0
          fsType: 'ext4'
          readOnly: false
---

kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306