kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # Le conteneur est toujour sur le master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - "true"
      # Définition du conteneur MySQL 
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 1500m
            memory: 1500Mi
          requests:
            cpu: 1500m
            memory: 1000Mi
        volumeMounts: 
        - name: sql-db
          mountPath: /var/lib/mysql
          subPath: "mysql"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      # Stockage de la base de données dur un disque réseau
      volumes:
      - name: sql-db
        iscsi:
          targetPortal: 10.0.0.3
          iqn: iqn.2003-01.org.linux-iscsi.debian.x8664:sn.dd15bcd23550
          lun: 0
          fsType: 'ext4'
          readOnly: false
---
# Service MySQL
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306