#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql-pv
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: slow
#---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  #volumeName: mysql-iscsi-pv
  storageClassName: mysql-iscsi-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  
  