kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: mchauvel/php-pdo-mysql:7.1-apache #php:7.4-apache
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 150m
        volumeMounts: 
        - name: nfs-www
          mountPath: /var/www/html
      volumes:
      - name: nfs-www
        nfs:
          server: 10.0.0.3
          path: /var/nfs/www
---

kind: Service
apiVersion: v1
metadata:
  name: httpd-service
spec:
  selector:
    app: httpd
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 80
  type: NodePort
---

#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: web-autoscaling
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: web-deployment
#  minReplicas: 2
#  maxReplicas: 25
#  targetCPUUtilizationPercentage: 75

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: httpd-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpd-deployment
  minReplicas: 2
  maxReplicas: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 250
        periodSeconds: 5
      selectPolicy: Max
---

